version: "2.4"
services:
  caller:
    build:
      context: ./celery-worker
      dockerfile: Dockerfile.caller
      args:
        - CELERY_VERSION=4.1.1
        - CELERY_BROKER_URL=amqp://guest@broker:5671
    command: ["--times=10"]
    depends_on:
      - worker
  worker:
    build:
      context: ./celery-worker
      args:
        - CELERY_VERSION=4.1.1
        - CELERY_BROKER_URL=amqp://guest@broker:5671
    command: ["-A=test_celery", "--loglevel=INFO"]
    depends_on:
      - broker
  broker:
    build:
      context: ./rabbitmq
      args:
        - RABBITMQ_HOSTNAME=broker
        - RABBITMQ_NAME=rabbit
